name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.12
        architecture: x64
    - run: pip install nox==2024.10.9
    - run: pip install poetry==2.0.1
    - run: poetry self add poetry-plugin-export
    - run: nox
    env:
      SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
